### ISSUE TITLE
Removing objects in the fence

### ISSUE THREAD

**Issue by Logoniuss** [Twometer/NoFences#13]
good day
Please do, when I move the folder to the fence, so that a link to the object is added to the fence, and not a physical object,

when I want to remove an object from the fences, the physical object on the desktop is also deleted.

I hope I have explained clearly. It is necessary to make sure that when transferring an object to the fence, a link is made to a file or folder for copying.

Or make the function of removing objects from fences.

Thanks for your work.

**Comment by Twometer** [comment]
Hi,
The fence only stores references to the file. When you do a right-click on the item however, you get the normal Windows Explorer menu. Clicking Delete on there actually deletes the file, since it is Windows Explorer.

What you want to do is shift + right-click on the item. This will open the fence-specific menu, including an item called `Delete item` which only deletes the _reference_, not the _file_ itself.

I understand that this is not the most intuitive way of handling the situation, and will definitely need see a UX improvement.

Hope this helps

**Comment by Logoniuss** [comment]
Thanks, it works, I did not know about this key combination.

**Comment by Twometer** [comment]
Glad it worked.
In a future release, I'll try to make this more intuitive. Also, there should be a documentation page where the usage is explained so confusions like this don't occur anymore.
