### ISSUE TITLE
Scaling for High DPI

### ISSUE THREAD

**Issue by 42Mockingjay** [Twometer/NoFences#23]

**Comment by Twometer** [comment]
Do you mean scaling for HiDPI screens?

**Comment by GordnCZ** [comment]
@42Mockingjay That's "just" the new Windows 11 thing.
It would probably need to be moved to new API for the context menu to look the same.

**Comment by emerysteele** [comment]
Are you referring to the conext menu text being a bit fuzzy/blurry?

If so, I think it might be the app is not re-adjusting to different display scalings.

It looks fine on my end with 100% scaling, but if set to higher (125% or 150% or 175%) it gets progressively blurry. I think with some code changes it might be possible to have it re-render for different scaling. I'm not super familiar with c# desktop apps though so not sure how that would be done.

Can maybe check your display scaling options to see if that is what is causing it? Right click on your Desktop, choose `Display settings`. Then click on your screen + scroll down to `Scale and layout`. See what % it's at.

If you mean the format/layout of the context menu, yeah that would require api changes. Might break compatibility with running NoFences on older Windows. Unless there is a way to programatically chose which kind of context menu is shown, depending on the OS
![1mGZPbZXmR](https://user-images.githubusercontent.com/1169001/168688264-165fcc9e-4394-4271-8c88-dcaa0a36a03b.png)
![7RuBWptP1H](https://user-images.githubusercontent.com/1169001/168688266-5969ef1d-de41-4366-84dc-43bd444a6ff7.png)
.

**Comment by Twometer** [comment]
Programatically opening the context menu on Windows is a huge pain. If you look into the `ShellContextMenu.cs` that I got from CodeProject, which has over 1500 lines of code, you can see that.

I'm going to see if I can do something like this for the modern Windows 11 context menu and show the appropriate one depending on the current OS version. However, I will move that part to a separate issue, and address that in the next major update (v2.0.0)

I'm also reopening this issue as the scaling issue, since NoFences should work on all scaling factors.

**Comment by GordnCZ** [comment]
@Twometer At this point, wouldn't it be better to write own context menu that would also be designed to fit the set style of fences?

But yeah, that's already different issue.

**Comment by Twometer** [comment]
@GordnCZ Yes that would indeed be better, as it would also remove the need for having Rightclick and Shift+Rightclick to access two different context menus, but then we'd have to build the menu from scratch, which can be difficult due to some apps like Notepad++ registering custom items.

However, I think we should continue discussing context menus in #29, as the scaling issue is already being worked on in #32 :)
